#logging.level.org.springframework: DEBUG
#logging.level.: DEBUG
spring:
  datasource:
    url:  jdbc:mysql://127.0.0.1:3306/test
    username: root
    password:
    driverClassName: com.mysql.jdbc.Driver
# JPA
jpa:
  hibernate:
  #ddl-auto: update
  ddl-auto: create-drop
  show-sql: true
# Thymeleaf
thymeleaf:
  cache: false